version: '3.4'

services:
  businesstrips.webapp:
    image: ${DOCKER_REGISTRY-}businesstripswebapp
    build:
      context: .
      dockerfile: BusinessTrips.WebApp/Dockerfile
    depends_on: 
      - db

  db:
    image: microsoft/mssql-server-linux
    environment:
            SA_PASSWORD: "P@ssw0rd"
            ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    expose: 
      - "1433" 
